<?
$arPosition = array(
	
	'SIZE' => 54,
	'whatsapp.com' => array(1,7,'whatsapp'),
	'telegram.org' => array(4,6,'telegram'),
	'viber.com' => array(0,7,'viber'),		
	'wechat.com' => array(3,0,'wechat'),
	'messenger.com' => array(0,0,'messenger'),
	'skype.com' => array(3,2,'skype'),
	'instagram.com' => array(3,6,'instagram'),
	'odnoklassniki.ru' => array(4,1,'odnoklassniki'),		
	'vk.com' => array(2,7,'vk'),
	'facebook.com' => array(1,0,'facebook'),
	'twitter.com' => array(2,0,'twitter'),
	'pinterest.com' => array(2,5,'pinterest'),
	'zen.yandex.ru' => array(1,5,'zen'),			 
	'tiktok.com' => array(0,5,'tiktok'),	 
	'snapchat.com' => array(4,0,'snapchat'),	 
	'twitch.tv' => array(3,5,'twitch'),	
	'youtube.com' => array(0,8,'youtube'),	

);
$arPositionOther = array(

	'vimeo.com' => array(1,4,'vimeo'),
	'appstore' => array(0,10,'appstore'),
	'apple' => array(1,10,'apple'),
	'googleplay' => array(2,10,'googleplay'),
	'android' => array(3,10,'android'),
	'windowsstore' => array(4,10,'windowsstore'),
	'windows' => array(4,11,'windows'),
	'xbox' => array(3,11,'xbox'),
	'playstation' => array(2,11,'playstation'),
	'steam' => array(1,11,'steam'),

	'behance' => array(1,2,'behance'),
	'dribbble' => array(2,2,'dribbble'),
	'trello' => array(3,1,'trello'),
	'slack' => array(4,2,'slack'),
	'b24' => array(4,3,'b24'),
	'bitrix24' => array(3,3,'bitrix24'),	
	'amocrm' => array(1,3,'amocrm'),

	'googledrive' => array(4,4,'googledrive'),
	'yandexdisk' => array(2,4,'yandexdisk'),
	'onedrive' => array(3,4,'onedrive'),

	'link' => array(0,6,'link'),
	'url' => array(1,6,'url'),
	'download' => array(2,6,'download'),
	'chat' => array(0,1,'chat'),
	'email' => array(1,1,'email'),
	'user' => array(2,1,'user'),
	'lock' => array(0,2,'lock'),
	'lock3' => array(0,3,'lock3'),
	'book' => array(2,8,'book'),
	'file' => array(3,8,'file'),
	'pdf' => array(4,8,'pdf'),
	'doc' => array(3,7,'doc'),
	'zip' => array(4,7,'zip'),
	
	'cart' => array(0,4,'cart'),
	'present' => array(0,9,'present'),
	'sale' => array(1,9,'sale'),
	'review' => array(2,9,'review'),
	'crm' => array(2,3,'crm'),		
	'map' => array(3,9,'map'),
	'order' => array(1,13,'order'),
	'pay' => array(0,13,'pay'),
	'search' => array(4,9,'search'),

	'calc' => array(4,5,'calc'),

	'goods' => array(3,14,'goods'),
	'kazanexpress' => array(2,13,'kazanexpress'),
	'beru' => array(0,14,'beru'),
	'avito' => array(3,13,'avito'),
	'aliexpress' => array(4,15,'aliexpress'),
	'ozon' => array(4,14,'ozon'),
	'la' => array(3,15,'la'),
	'yandexmarket' => array(1,14,'yandexmarket'),
	'wb' => array(2,15,'wb'),
	'cdek' => array(4,13,'cdek'),
	'youla' => array(1,15,'youla'),
	'tiu' => array(2,14,'tiu'),

	'br' => array(0,0,'br'),
	'brv' => array(0,0,'brv'),
	'br5' => array(0,0,'br5'),
	'brv5' => array(0,0,'brv5'),
	'br10' => array(0,0,'br10'),
	'brv10' => array(0,0,'brv10'),
	'br15' => array(0,0,'br15'),
	'brv15' => array(0,0,'brv15'),
	'br20' => array(0,0,'br20'),
	'brv20' => array(0,0,'brv20'),
	'br25' => array(0,0,'br25'),
	'brv25' => array(0,0,'brv25'),

);
?>